pylint:
  disable:
    - bare-except
    - unused-argument
    - pointless-string-statement
    - too-many-locals
    - too-many-arguments
    - protected-access
    - unused-variable
    - super-on-old-class
    
pep8:
  disable:
    - E1002
    
ignore-paths:
    - docs
    - logs
    - quokka/static
    - quokka/templates
    - quokka/themes
    - quokka/fixtures

requirements:
    - requirements.txt
    - requirements_test.txt
    
#max-line-length: 120
